version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: todos
      MYSQL_USER: aleks
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
